'use strict';

const { EventEmitter } = require('events');

// Mock child_process.spawn BEFORE requiring server so the bound `spawn` variable
// inside server.js gets the mock version.
jest.mock('child_process', () => ({ spawn: jest.fn() }));
jest.mock('pg', () => ({ Pool: jest.fn(() => ({ query: jest.fn() })) }));
jest.mock('../../lib/db', () => ({
  createPool: jest.fn(() => ({ query: jest.fn() })),
  getDatabaseUrl: jest.fn(),
}));
jest.mock('pgvector', () => ({ toSql: jest.fn((v) => v) }));

const { spawn } = require('child_process');
const { verifyWorkPushed } = require('../../server');

// Helper: create a fake child_process that emits stdout/stderr then exits.
function fakeProcEmitting({ stdout = '', stderr = '', exitCode = 0 } = {}) {
  const proc = new EventEmitter();
  proc.stdout = new EventEmitter();
  proc.stderr = new EventEmitter();

  setImmediate(() => {
    if (stdout) proc.stdout.emit('data', Buffer.from(stdout));
    if (stderr) proc.stderr.emit('data', Buffer.from(stderr));
    proc.emit('exit', exitCode);
  });

  return proc;
}

// Helper: make spawn return a sequence of fake processes for each successive call.
function mockSpawnSequence(responses) {
  let callIndex = 0;
  spawn.mockImplementation(() => {
    const r = responses[callIndex++] || { stdout: '', stderr: '', exitCode: 0 };
    return fakeProcEmitting(r);
  });
}

describe('verifyWorkPushed', () => {
  beforeEach(() => {
    spawn.mockReset();
  });

  it('returns ok:true when tree is clean and branch is not ahead', async () => {
    // Calls in order (for a single autogenerated file check, then status, then rev-list):
    // 1. git status --porcelain -- src/frontend/next-env.d.ts  -> empty (no modification)
    // 2. git status --porcelain --untracked-files=no           -> empty (clean tree)
    // 3. git rev-list --count @{u}..HEAD                       -> "0\n"
    mockSpawnSequence([
      { stdout: '', exitCode: 0 },  // autogenerated file probe
      { stdout: '', exitCode: 0 },  // git status
      { stdout: '0\n', exitCode: 0 }, // rev-list
    ]);

    const result = await verifyWorkPushed('/some/repo');
    expect(result).toEqual({ ok: true });
  });

  it('returns ok:false with reason when there are uncommitted tracked changes', async () => {
    mockSpawnSequence([
      { stdout: '', exitCode: 0 },              // autogenerated file probe
      { stdout: ' M README.md\n', exitCode: 0 }, // git status shows modifications
      { stdout: '0\n', exitCode: 0 },            // rev-list (not reached due to early return)
    ]);

    const result = await verifyWorkPushed('/some/repo');
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/uncommitted changes/i);
    expect(result.reason).toContain('README.md');
  });

  it('returns ok:false when git status exits with non-zero', async () => {
    mockSpawnSequence([
      { stdout: '', exitCode: 0 },         // autogenerated file probe
      { stdout: '', stderr: 'not a git repo', exitCode: 128 }, // git status fails
    ]);

    const result = await verifyWorkPushed('/some/repo');
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/git status failed/i);
    expect(result.reason).toContain('128');
  });

  it('returns ok:false when branch is ahead of upstream', async () => {
    mockSpawnSequence([
      { stdout: '', exitCode: 0 },   // autogenerated file probe
      { stdout: '', exitCode: 0 },   // git status clean
      { stdout: '2\n', exitCode: 0 }, // branch is 2 commits ahead
    ]);

    const result = await verifyWorkPushed('/some/repo');
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/ahead of upstream/i);
    expect(result.reason).toContain('2');
  });

  it('returns ok:false when rev-list exits with non-zero (no upstream)', async () => {
    mockSpawnSequence([
      { stdout: '', exitCode: 0 },  // autogenerated file probe
      { stdout: '', exitCode: 0 },  // git status clean
      { stdout: '', stderr: 'no upstream', exitCode: 128 }, // rev-list fails
    ]);

    const result = await verifyWorkPushed('/some/repo');
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/rev-list.*failed/i);
  });

  it('discards a modified autogenerated file before checking status', async () => {
    // Sequence: probe finds next-env.d.ts modified, checkout runs, then clean status
    const gitCalls = [];
    spawn.mockImplementation((_cmd, args) => {
      gitCalls.push(args.join(' '));
      // probe -> modified
      if (args.includes('status') && args.includes('src/frontend/next-env.d.ts')) {
        return fakeProcEmitting({ stdout: ' M src/frontend/next-env.d.ts\n', exitCode: 0 });
      }
      // checkout -> success
      if (args.includes('checkout')) {
        return fakeProcEmitting({ stdout: '', exitCode: 0 });
      }
      // final status -> clean
      if (args.includes('--untracked-files=no')) {
        return fakeProcEmitting({ stdout: '', exitCode: 0 });
      }
      // rev-list -> 0
      return fakeProcEmitting({ stdout: '0\n', exitCode: 0 });
    });

    const result = await verifyWorkPushed('/some/repo');
    expect(result).toEqual({ ok: true });
    expect(gitCalls.some((c) => c.includes('checkout'))).toBe(true);
  });

  it('does not checkout autogenerated file when it is unmodified', async () => {
    const gitCalls = [];
    spawn.mockImplementation((_cmd, args) => {
      gitCalls.push(args.join(' '));
      if (args.includes('src/frontend/next-env.d.ts')) {
        return fakeProcEmitting({ stdout: '', exitCode: 0 }); // not modified
      }
      if (args.includes('--untracked-files=no')) {
        return fakeProcEmitting({ stdout: '', exitCode: 0 });
      }
      return fakeProcEmitting({ stdout: '0\n', exitCode: 0 });
    });

    await verifyWorkPushed('/some/repo');
    expect(gitCalls.some((c) => c.includes('checkout'))).toBe(false);
  });

  it('returns ok:false when rev-list returns NaN', async () => {
    mockSpawnSequence([
      { stdout: '', exitCode: 0 },
      { stdout: '', exitCode: 0 },
      { stdout: 'bad output\n', exitCode: 0 },
    ]);

    const result = await verifyWorkPushed('/some/repo');
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/ahead of upstream/i);
  });
});
